### ISSUE TITLE
OpenHack

### ISSUE THREAD

**Issue by poteto** [HackUpOrg/Melbourne.AU#4]
@PureKrome, not sure if you've already seen [OpenHack](http://openhack.github.io/), but it's a similar concept that's already pretty well established.

Perhaps we could brand ourselves as [OpenHack Melbourne](http://openhack.github.io/yours/) for better reach? There isn't a Melbourne one yet, so we could be filling a good spot.

**Comment by PureKrome** [comment]
PR finally created :) now we wait...

**Comment by PureKrome** [comment]
Merged. We are alive!
