### ISSUE TITLE
Sign Up (Thrs March 12th)

### ISSUE THREAD

**Issue by PureKrome** [HackUpOrg/Melbourne.AU#5]
Time: 6:00pm - 8:00/8:30pm  
Space: [Electron Workshop](http://www.electronworkshop.com.au/)
Address: [31 Arden St, North Melbourne VIC 3051](https://www.google.com.au/maps/place/Electron+Workshop+-+Coworking+Space/@-37.801309,144.950752,15z/data=!4m2!3m1!1s0x0:0x83bc7c2c3fb10a86?sa=X&ei=2RKJVLSUKITpmQX1hoLIBQ&ved=0CHwQ_BIwCw)

**Comment by PureKrome** [comment]
In :)  @frankradocaj - can you please confirm the venue details are still OK / booked?

**Comment by frankradocaj** [comment]
Thursday, 12th March 6pm @ Electron Workshop is confirmed. Looking forward to it!

**Comment by poteto** [comment]
Will have to re-confirm, but sounds good to me! Going to work on my [ember-cli addon](https://github.com/poteto/ember-cli-flash) :)

**Comment by poteto** [comment]
Won't be able to make this one, I have to go home and pack!
